# Generated by Django 3.2.5 on 2023-08-17 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_category', models.CharField(max_length=30, verbose_name='Crime Category')),
                ('crime_short_code', models.CharField(max_length=4, verbose_name='Crime Short Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name_plural': 'Crime Categories',
            },
        ),
        migrations.CreateModel(
            name='CrimeReportBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurance_book_number', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='Occurance Book Number (OB Number)')),
                ('name_of_crime', models.CharField(max_length=100, verbose_name='Name of Crime')),
                ('crime_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('name_of_criminal', models.CharField(max_length=60, null=True, verbose_name='Name of Criminal')),
                ('criminal_id_number', models.IntegerField(null=True)),
                ('upload_criminal_photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('category_of_crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nawaapp.crimecategory', verbose_name='Category of Crime')),
            ],
            options={
                'verbose_name_plural': 'Crime Report Book',
            },
        ),
    ]
