# Generated by Django 5.1.4 on 2025-02-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimereportbook',
            options={'ordering': ['-date_updated'], 'verbose_name_plural': 'Crime Report Books'},
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age of Criminal'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='date_of_arrest',
            field=models.DateField(null=True, verbose_name='Date of Arrest'),
        ),
        migrations.CreateModel(
            name='CrimeWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Witness')),
                ('contact_information', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Information')),
                ('statement', models.TextField(verbose_name='Witness Statement')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('crime_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nawaapp.crimereportbook', verbose_name='Related Crime Report')),
            ],
            options={
                'verbose_name_plural': 'Crime Witnesses',
            },
        ),
    ]
