# Generated by Django 5.2.8 on 2025-11-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0002_alter_crimereportbook_options_crimereportbook_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereportbook',
            name='criminal_id_number',
            field=models.IntegerField(null=True, verbose_name='Criminal Identity Number'),
        ),
    ]
