# Generated by Django 5.2.8 on 2025-11-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0003_alter_crimereportbook_criminal_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereportbook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Crime Description'),
        ),
    ]
