# Generated by Django 5.2.8 on 2025-11-10 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0004_crimereportbook_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereportbook',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned At'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Officer'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed At'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Escalated At'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='last_status_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Status Change'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('triaged', 'Triaged'), ('escalated', 'Escalated'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Triaged At'),
        ),
    ]
