# Generated by Django 5.2.8 on 2025-11-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0005_crimereportbook_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReportBookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('triaged', 'Triaged'), ('escalated', 'Escalated'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('triaged', 'Triaged'), ('escalated', 'Escalated'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20, null=True)),
                ('from_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('to_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_report_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('from_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_report_audit_from_assignments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='nawaapp.crimereportbook')),
                ('to_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_report_audit_to_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crime Report Audit Log',
                'verbose_name_plural': 'Crime Report Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
