# Generated by Django 5.2.8 on 2025-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0006_crimereportbookauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereportbook',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='location_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Description'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Name'),
        ),
        migrations.AddField(
            model_name='crimereportbook',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
