# Generated by Django 5.2.8 on 2025-11-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0007_crimereportbook_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereportbook',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County'),
        ),
    ]
