# Generated by Django 5.1.4 on 2025-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0009_alertevent_alertsubscription_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Push Token'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
