# Generated by Django 5.1.4 on 2025-11-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0012_neighborhood_polygon_membership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
