# Generated by Django 5.1.4 on 2025-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0013_alter_devicetoken_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereportbook',
            name='evidence_video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
