# Generated by Django 4.2.27 on 2025-12-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0016_anonymoussession_securityorgwhitelist_devicefingerprint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anonymoussession',
            new_name='nawaapp_ano_device__053c7e_idx',
            old_name='nawaapp_anon_dev_fp_idx',
        ),
        migrations.RenameIndex(
            model_name='anonymoussession',
            new_name='nawaapp_ano_ip_addr_7c090e_idx',
            old_name='nawaapp_anon_ip_addr_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='nawaapp_dev_fingerp_5af7e3_idx',
            old_name='nawaapp_dev_fp_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='devicefingerprint',
            new_name='nawaapp_dev_ip_addr_bf97a2_idx',
            old_name='nawaapp_dev_fp_ip_idx',
        ),
    ]
