# Generated by Django 4.2.27 on 2025-12-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nawaapp', '0017_rename_nawaapp_anon_dev_fp_idx_nawaapp_ano_device__053c7e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereportbook',
            name='assigned_organization',
            field=models.ForeignKey(blank=True, help_text='Organization responsible for this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='nawaapp.securityorgwhitelist', verbose_name='Assigned Organization'),
        ),
    ]
