# Canonical county alias mapping for Kenya.
# Keys must be lowercase strings; values are the canonical "X County" string.

COUNTY_ALIAS = {
	# Nairobi
	'westlands': 'Nairobi County',
	'dagoretti north': 'Nairobi County',
	'dagoretti south': 'Nairobi County',
	'langata': 'Nairobi County',
	'kibra': 'Nairobi County',
	'roysambu': 'Nairobi County',
	'kasarani': 'Nairobi County',
	'ruaraka': 'Nairobi County',
	'embakasi north': 'Nairobi County',
	'embakasi east': 'Nairobi County',
	'embakasi west': 'Nairobi County',
	'embakasi central': 'Nairobi County',
	'embakasi south': 'Nairobi County',
	'makadara': 'Nairobi County',
	'kamukunji': 'Nairobi County',
	'starehe': 'Nairobi County',
	'mathare': 'Nairobi County',
	'nairobi': 'Nairobi County',

	# Mombasa
	'jomvu': 'Mombasa County',
	'kisauni': 'Mombasa County',
	'nyali': 'Mombasa County',
	'changamwe': 'Mombasa County',
	'likoni': 'Mombasa County',
	'mvita': 'Mombasa County',
	'mombasa': 'Mombasa County',

	# Kiambu
	'thika town': 'Kiambu County',
	'gatundu north': 'Kiambu County',
	'gatundu south': 'Kiambu County',
	'juja': 'Kiambu County',
	'ruiru': 'Kiambu County',
	'kiambu': 'Kiambu County',
	'githunguri': 'Kiambu County',
	'limuru': 'Kiambu County',
	'lantana': 'Kiambu County',  # occasionally appears as typo; map to Kiambu
	'kabete': 'Kiambu County',
	'kikuyu': 'Kiambu County',
	'kiambaa': 'Kiambu County',

	# Nakuru
	'naivasha': 'Nakuru County',
	'gilgil': 'Nakuru County',
	'nakuru town east': 'Nakuru County',
	'nakuru town west': 'Nakuru County',
	'subukia': 'Nakuru County',
	'rongai': 'Nakuru County',
	'kuresoi north': 'Nakuru County',
	'kuresoi south': 'Nakuru County',
	'bahati': 'Nakuru County',
	'molo': 'Nakuru County',
	'njoro': 'Nakuru County',
	'nakuru': 'Nakuru County',

	# Kisumu
	'kisumu central': 'Kisumu County',
	'kisumu west': 'Kisumu County',
	'kisumu east': 'Kisumu County',
	'nyando': 'Kisumu County',
	'nyakach': 'Kisumu County',
	'seme': 'Kisumu County',
	'muhoroni': 'Kisumu County',
	'kisumu': 'Kisumu County',

	# Uasin Gishu
	'ainabkoi': 'Uasin Gishu County',
	'kapseret': 'Uasin Gishu County',
	'kesses': 'Uasin Gishu County',
	'moiben': 'Uasin Gishu County',
	'soy': 'Uasin Gishu County',
	'turbo': 'Uasin Gishu County',
	'uasin gishu': 'Uasin Gishu County',

	# Kakamega
	'likuyani': 'Kakamega County',
	'lumakanda': 'Kakamega County',
	'malava': 'Kakamega County',
	'navakholo': 'Kakamega County',
	'lurambi': 'Kakamega County',
	'mumias east': 'Kakamega County',
	'mumias west': 'Kakamega County',
	'matungu': 'Kakamega County',
	'ikolomani': 'Kakamega County',
	'shaka': 'Kakamega County',
	'kakamega': 'Kakamega County',

	# Nyeri
	'nyeri town': 'Nyeri County',
	'kieni': 'Nyeri County',
	'tetu': 'Nyeri County',
	'mathira': 'Nyeri County',
	'mukurweini': 'Nyeri County',
	'othaya': 'Nyeri County',
	'nyeri': 'Nyeri County',

	# Machakos
	'athiriver': 'Machakos County',
	'mavoko': 'Machakos County',
	'kangundo': 'Machakos County',
	'matungulu': 'Machakos County',
	'masinga': 'Machakos County',
	'mwala': 'Machakos County',
	'yatta': 'Machakos County',
	'kathiani': 'Machakos County',
	'machakos': 'Machakos County',

	# Kajiado
	'kajiado north': 'Kajiado County',
	'kajiado east': 'Kajiado County',
	'kajiado west': 'Kajiado County',
	'kajiado central': 'Kajiado County',
	'loitokitok': 'Kajiado County',
	'ongata rongai': 'Kajiado County',
	'kitengela': 'Kajiado County',
	'kajiado': 'Kajiado County',

	# Kilifi
	'kilifi north': 'Kilifi County',
	'kilifi south': 'Kilifi County',
	'malindi': 'Kilifi County',
	'kaloleni': 'Kilifi County',
	'rabai': 'Kilifi County',
	'ganjoni': 'Kilifi County',
	'tezo': 'Kilifi County',
	'magarini': 'Kilifi County',
	'kilifi': 'Kilifi County',

	# Meru (also covered earlier in code)
	'imenti north': 'Meru County',
	'imenti south': 'Meru County',
	'imenti central': 'Meru County',
	'igembe north': 'Meru County',
	'igembe south': 'Meru County',
	'igembe central': 'Meru County',
	'tigania east': 'Meru County',
	'tigania west': 'Meru County',
	'buuri': 'Meru County',
	'meru': 'Meru County',
}

# Base county names -> canonical for all 47 counties
COUNTY_ALIAS.update({
	'mombasa': 'Mombasa County',
	'kwale': 'Kwale County',
	'kilifi': 'Kilifi County',
	'tana river': 'Tana River County',
	'lamu': 'Lamu County',
	'taita-taveta': 'Taita-Taveta County',
	'taita taveta': 'Taita-Taveta County',
	'garissa': 'Garissa County',
	'wajir': 'Wajir County',
	'mandera': 'Mandera County',
	'marsabit': 'Marsabit County',
	'isiolo': 'Isiolo County',
	'meru': 'Meru County',
	'tharaka-nithi': 'Tharaka-Nithi County',
	'tharaka nithi': 'Tharaka-Nithi County',
	'embu': 'Embu County',
	'kitui': 'Kitui County',
	'machakos': 'Machakos County',
	'makueni': 'Makueni County',
	'nyandarua': 'Nyandarua County',
	'nyeri': 'Nyeri County',
	'kirinyaga': 'Kirinyaga County',
	"murang'a": "Murang'a County",
	'muranga': "Murang'a County",
	'kiambu': 'Kiambu County',
	'turkana': 'Turkana County',
	'west pokot': 'West Pokot County',
	'samburu': 'Samburu County',
	'trans nzoia': 'Trans Nzoia County',
	'uasin gishu': 'Uasin Gishu County',
	'elgeyo-marakwet': 'Elgeyo-Marakwet County',
	'elgeyo marakwet': 'Elgeyo-Marakwet County',
	'nandi': 'Nandi County',
	'baringo': 'Baringo County',
	'laikipia': 'Laikipia County',
	'nakuru': 'Nakuru County',
	'narok': 'Narok County',
	'kajiado': 'Kajiado County',
	'kericho': 'Kericho County',
	'bomet': 'Bomet County',
	'kakamega': 'Kakamega County',
	'vihiga': 'Vihiga County',
	'bungoma': 'Bungoma County',
	'busia': 'Busia County',
	'siaya': 'Siaya County',
	'kisumu': 'Kisumu County',
	'homa bay': 'Homa Bay County',
	'homabay': 'Homa Bay County',
	'migori': 'Migori County',
	'kisii': 'Kisii County',
	'nyamira': 'Nyamira County',
	'nairobi': 'Nairobi County',
})


