# Canonical county alias mapping for Kenya.
# Keys must be lowercase strings; values are the canonical "X County" string.

COUNTY_ALIAS = {
	# Nairobi
	'westlands': 'Nairobi County',
	'dagoretti north': 'Nairobi County',
	'dagoretti south': 'Nairobi County',
	'langata': 'Nairobi County',
	'kibra': 'Nairobi County',
	'roysambu': 'Nairobi County',
	'kasarani': 'Nairobi County',
	'ruaraka': 'Nairobi County',
	'embakasi north': 'Nairobi County',
	'embakasi east': 'Nairobi County',
	'embakasi west': 'Nairobi County',
	'embakasi central': 'Nairobi County',
	'embakasi south': 'Nairobi County',
	'makadara': 'Nairobi County',
	'kamukunji': 'Nairobi County',
	'starehe': 'Nairobi County',
	'mathare': 'Nairobi County',
	'nairobi': 'Nairobi County',

	# Mombasa
	'jomvu': 'Mombasa County',
	'kisauni': 'Mombasa County',
	'nyali': 'Mombasa County',
	'changamwe': 'Mombasa County',
	'likoni': 'Mombasa County',
	'mvita': 'Mombasa County',
	'mombasa': 'Mombasa County',

	# Kiambu
	'thika town': 'Kiambu County',
	'gatundu north': 'Kiambu County',
	'gatundu south': 'Kiambu County',
	'juja': 'Kiambu County',
	'ruiru': 'Kiambu County',
	'kiambu': 'Kiambu County',
	'githunguri': 'Kiambu County',
	'limuru': 'Kiambu County',
	'lantana': 'Kiambu County',  # occasionally appears as typo; map to Kiambu
	'kabete': 'Kiambu County',
	'kikuyu': 'Kiambu County',
	'kiambaa': 'Kiambu County',

	# Nakuru
	'naivasha': 'Nakuru County',
	'gilgil': 'Nakuru County',
	'nakuru town east': 'Nakuru County',
	'nakuru town west': 'Nakuru County',
	'subukia': 'Nakuru County',
	'rongai': 'Nakuru County',
	'kuresoi north': 'Nakuru County',
	'kuresoi south': 'Nakuru County',
	'bahati': 'Nakuru County',
	'molo': 'Nakuru County',
	'njoro': 'Nakuru County',
	'nakuru': 'Nakuru County',

	# Kisumu
	'kisumu central': 'Kisumu County',
	'kisumu west': 'Kisumu County',
	'kisumu east': 'Kisumu County',
	'nyando': 'Kisumu County',
	'nyakach': 'Kisumu County',
	'seme': 'Kisumu County',
	'muhoroni': 'Kisumu County',
	'kisumu': 'Kisumu County',

	# Uasin Gishu
	'ainabkoi': 'Uasin Gishu County',
	'kapseret': 'Uasin Gishu County',
	'kesses': 'Uasin Gishu County',
	'moiben': 'Uasin Gishu County',
	'soy': 'Uasin Gishu County',
	'turbo': 'Uasin Gishu County',
	'uasin gishu': 'Uasin Gishu County',

	# Kakamega
	'likuyani': 'Kakamega County',
	'lumakanda': 'Kakamega County',
	'malava': 'Kakamega County',
	'navakholo': 'Kakamega County',
	'lurambi': 'Kakamega County',
	'mumias east': 'Kakamega County',
	'mumias west': 'Kakamega County',
	'matungu': 'Kakamega County',
	'ikolomani': 'Kakamega County',
	'shaka': 'Kakamega County',
	'kakamega': 'Kakamega County',

	# Nyeri
	'nyeri town': 'Nyeri County',
	'kieni': 'Nyeri County',
	'tetu': 'Nyeri County',
	'mathira': 'Nyeri County',
	'mukurweini': 'Nyeri County',
	'othaya': 'Nyeri County',
	'nyeri': 'Nyeri County',

	# Machakos
	'athiriver': 'Machakos County',
	'mavoko': 'Machakos County',
	'kangundo': 'Machakos County',
	'matungulu': 'Machakos County',
	'masinga': 'Machakos County',
	'mwala': 'Machakos County',
	'yatta': 'Machakos County',
	'kathiani': 'Machakos County',
	'machakos': 'Machakos County',

	# Kajiado
	'kajiado north': 'Kajiado County',
	'kajiado east': 'Kajiado County',
	'kajiado west': 'Kajiado County',
	'kajiado central': 'Kajiado County',
	'loitokitok': 'Kajiado County',
	'ongata rongai': 'Kajiado County',
	'kitengela': 'Kajiado County',
	'kajiado': 'Kajiado County',

	# Kilifi
	'kilifi north': 'Kilifi County',
	'kilifi south': 'Kilifi County',
	'malindi': 'Kilifi County',
	'kaloleni': 'Kilifi County',
	'rabai': 'Kilifi County',
	'ganjoni': 'Kilifi County',
	'tezo': 'Kilifi County',
	'magarini': 'Kilifi County',
	'kilifi': 'Kilifi County',

	# Meru (also covered earlier in code)
	'imenti north': 'Meru County',
	'imenti south': 'Meru County',
	'imenti central': 'Meru County',
	'igembe north': 'Meru County',
	'igembe south': 'Meru County',
	'igembe central': 'Meru County',
	'tigania east': 'Meru County',
	'tigania west': 'Meru County',
	'buuri': 'Meru County',
	'meru': 'Meru County',
}

# Base county names -> canonical for all 47 counties
COUNTY_ALIAS.update({
	'mombasa': 'Mombasa County',
	'kwale': 'Kwale County',
	'kilifi': 'Kilifi County',
	'tana river': 'Tana River County',
	'lamu': 'Lamu County',
	'taita-taveta': 'Taita-Taveta County',
	'taita taveta': 'Taita-Taveta County',
	'garissa': 'Garissa County',
	'wajir': 'Wajir County',
	'mandera': 'Mandera County',
	'marsabit': 'Marsabit County',
	'isiolo': 'Isiolo County',
	'meru': 'Meru County',
	'tharaka-nithi': 'Tharaka-Nithi County',
	'tharaka nithi': 'Tharaka-Nithi County',
	'elegeyo-marakwet': 'Elgeyo-Marakwet County',
	'elegeyo marakwet': 'Elgeyo-Marakwet County',
	'embu': 'Embu County',
	'kitui': 'Kitui County',
	'machakos': 'Machakos County',
	'makueni': 'Makueni County',
	'nyandarua': 'Nyandarua County',
	'nyeri': 'Nyeri County',
	'kirinyaga': 'Kirinyaga County',
	"murang'a": "Murang'a County",
	'muranga': "Murang'a County",
	'kiambu': 'Kiambu County',
	'turkana': 'Turkana County',
	'west pokot': 'West Pokot County',
	'samburu': 'Samburu County',
	'trans nzoia': 'Trans Nzoia County',
	'uasin gishu': 'Uasin Gishu County',
	'elgeyo-marakwet': 'Elgeyo-Marakwet County',
	'elgeyo marakwet': 'Elgeyo-Marakwet County',
	'nandi': 'Nandi County',
	'baringo': 'Baringo County',
	'laikipia': 'Laikipia County',
	'nakuru': 'Nakuru County',
	'narok': 'Narok County',
	'kajiado': 'Kajiado County',
	'kericho': 'Kericho County',
	'bomet': 'Bomet County',
	'kakamega': 'Kakamega County',
	'vihiga': 'Vihiga County',
	'bungoma': 'Bungoma County',
	'busia': 'Busia County',
	'siaya': 'Siaya County',
	'kisumu': 'Kisumu County',
	'homa bay': 'Homa Bay County',
	'homabay': 'Homa Bay County',
	'migori': 'Migori County',
	'kisii': 'Kisii County',
	'nyamira': 'Nyamira County',
	'nairobi': 'Nairobi County',
})

COUNTY_ALIAS.update({
    'ainabkoi': 'Uasin Gishu County',
    'ainamoi': 'Kericho County',
    'aldai': 'Nandi County',
    'alego usonga': 'Siaya County',
    'awendo': 'Migori County',
    'bahati': 'Nakuru County',
    'balambala': 'Garissa County',
    'banissa': 'Mandera County',
    'baringo central': 'Baringo County',
    'baringo north': 'Baringo County',
    'baringo south': 'Baringo County',
    'belgut': 'Kericho County',
    'bobasi': 'Kisii County',
    'bomachoge borabu': 'Kisii County',
    'bomachoge chache': 'Kisii County',
    'bomet central': 'Bomet County',
    'bomet east': 'Bomet County',
    'bonchari': 'Kisii County',
    'bondo': 'Siaya County',
    'borabu': 'Nyamira County',
    'budalangi': 'Busia County',
    'bumula': 'Bungoma County',
    'bura': 'Tana River County',
    'buret': 'Kericho County',
    'butere': 'Kakamega County',
    'butula': 'Busia County',
    'buuri': 'Meru County',
    'cental imenti': 'Meru County',
    'changamwe': 'Mombasa County',
    'chepalungu': 'Bomet County',
    'cherangany': 'Trans Nzoia County',
    'chesumei': 'Nandi County',
    'dadaab': 'Garissa County',
    'dagoretti': 'Nairobi County',
    'dujis': 'Garissa County',
    'eldama ravine': 'Baringo County',
    'eldas': 'Wajir County',
    'embakasi central': 'Nairobi County',
    'embakasi east': 'Nairobi County',
    'embakasi north': 'Nairobi County',
    'embakasi south': 'Nairobi County',
    'embakasi west': 'Nairobi County',
    'emgwen': 'Nandi County',
    'emuhaya': 'Vihiga County',
    'emurua dikirr': 'Narok County',
    'endebess': 'Trans Nzoia County',
    'fafi': 'Garissa County',
    'funyula': 'Busia County',
    'gachoka': 'Embu County',
    'galole': 'Tana River County',
    'ganze': 'Kilifi County',
    'garsen': 'Tana River County',
    'gatanga': "Murang'a County",
    'gatundu north': 'Kiambu County',
    'gatundu south': 'Kiambu County',
    'gem': 'Siaya County',
    'gichugu': 'Kirinyaga County',
    'gilgil': 'Nakuru County',
    'githunguri': 'Kiambu County',
    'hamisi': 'Vihiga County',
    'homa bay': 'Homa Bay County',
    'igembe central': 'Meru County',
    'igembe north': 'Meru County',
    'igembe south': 'Meru County',
    'ijara': 'Garissa County',
    'ikolomani': 'Kakamega County',
    'isiolo north': 'Isiolo County',
    'isiolo south': 'Isiolo County',
    'jomvu': 'Mombasa County',
    'juja': 'Kiambu County',
    'kabete': 'Kiambu County',
    'kabondo kasipul': 'Homa Bay County',
    'kabuchai': 'Bungoma County',
    'kacheliba': 'West Pokot County',
    'kaiti': 'Makueni County',
    'kajiado central': 'Kajiado County',
    'kajiado east': 'Kajiado County',
    'kajiado north': 'Kajiado County',
    'kajiado south': 'Kajiado County',
    'kajiado west': 'Kajiado County',
    'kaloleni': 'Kilifi County',
    'kamukunji': 'Nairobi County',
    'kandara': "Murang'a County",
    'kanduyi': 'Bungoma County',
    'kangema': "Murang'a County",
    'kangundo': 'Machakos County',
    'kapenguria': 'West Pokot County',
    'kapseret': 'Uasin Gishu County',
    'karachuonyo': 'Homa Bay County',
    'kasarani': 'Nairobi County',
    'kasipul': 'Homa Bay County',
    'kathiani': 'Machakos County',
    'keiyo north': 'Elgeyo-Marakwet County',
    'keiyo south': 'Elgeyo-Marakwet County',
    'kesses': 'Uasin Gishu County',
    'khwisero': 'Kakamega County',
    'kiambaa': 'Kiambu County',
    'kiambu': 'Kiambu County',
    'kibra': 'Nairobi County',
    'kibwezi east': 'Makueni County',
    'kibwezi west': 'Makueni County',
    'kieni': 'Nyeri County',
    'kigumo': "Murang'a County",
    'kiharu': "Murang'a County",
    'kikuyu': 'Kiambu County',
    'kilgoris': 'Narok County',
    'kilifi north': 'Kilifi County',
    'kilifi south': 'Kilifi County',
    'kilimani': 'Nairobi County',
    'kilome': 'Makueni County',
    'kimilili': 'Bungoma County',
    'kiminini': 'Trans Nzoia County',
    'kinango': 'Kwale County',
    'kinangop': 'Nyandarua County',
    'kipipiri': 'Nyandarua County',
    'kipkelion east': 'Kericho County',
    'kipkelion west': 'Kericho County',
    'kirinyaga central': 'Kirinyaga County',
    'kisauni': 'Mombasa County',
    'kisumu central': 'Kisumu County',
    'kisumu east': 'Kisumu County',
    'kisumu west': 'Kisumu County',
    'kitui central': 'Kitui County',
    'kitui east': 'Kitui County',
    'kitui rural': 'Kitui County',
    'kitui south': 'Kitui County',
    'kitui west': 'Kitui County',
    'kitutu chache north': 'Kisii County',
    'kitutu chache south': 'Kisii County',
    'kitutu masaba': 'Nyamira County',
    'konoin': 'Bomet County',
    'kuresoi north': 'Nakuru County',
    'kuresoi south': 'Nakuru County',
    'kuria east': 'Migori County',
    'kuria west': 'Migori County',
    'kwanza': 'Trans Nzoia County',
    'lafey': 'Mandera County',
    'lagdera': 'Garissa County',
    'laikipia east': 'Laikipia County',
    'laikipia north': 'Laikipia County',
    'laikipia west': 'Laikipia County',
    'laisamis': 'Marsabit County',
    'lamu east': 'Lamu County',
    'lamu west': 'Lamu County',
    'langata': 'Nairobi County',
    'lari': 'Kiambu County',
    'likoni': 'Mombasa County',
    'likuyani': 'Kakamega County',
    'limuru': 'Kiambu County',
    'loima': 'Turkana County',
    'luanda': 'Vihiga County',
    'lugari': 'Kakamega County',
    'lunga lunga': 'Kwale County',
    'lurambi': 'Kakamega County',
    'maara': 'Tharaka-Nithi County',
    'machakos town': 'Machakos County',
    'magarini': 'Kilifi County',
    'makadara': 'Nairobi County',
    'makueni': 'Makueni County',
    'malava': 'Kakamega County',
    'malindi': 'Kilifi County',
    'mandera east': 'Mandera County',
    'mandera north': 'Mandera County',
    'mandera south': 'Mandera County',
    'mandera west': 'Mandera County',
    'manyatta': 'Embu County',
    'maragwa': "Murang'a County",
    'marakwet east': 'Elgeyo-Marakwet County',
    'marakwet west': 'Elgeyo-Marakwet County',
    'masinga': 'Machakos County',
    'matayos': 'Busia County',
    'mathare': 'Nairobi County',
    'mathioya': "Murang'a County",
    'mathira': 'Nyeri County',
    'matuga': 'Kwale County',
    'matungu': 'Kakamega County',
    'matungulu': 'Machakos County',
    'mavoko': 'Machakos County',
    'mbooni': 'Makueni County',
    'mogotio': 'Baringo County',
    'moiben': 'Uasin Gishu County',
    'molo': 'Nakuru County',
    'mosop': 'Nandi County',
    'moyale': 'Marsabit County',
    'msambweni': 'Kwale County',
    'mt. elgon': 'Bungoma County',
    'muhoroni': 'Kisumu County',
    'mukurweni': 'Nyeri County',
    'mumias east': 'Kakamega County',
    'mumias west': 'Kakamega County',
    'mvita': 'Mombasa County',
    'mwala': 'Machakos County',
    'mwatate': 'Taita-Taveta County',
    'mwea': 'Kirinyaga County',
    'mwingi east': 'Kitui County',
    'mwingi north': 'Kitui County',
    'mwingi west': 'Kitui County',
    'naivasha': 'Nakuru County',
    'nakuru town east': 'Nakuru County',
    'nakuru town west': 'Nakuru County',
    'nambale': 'Busia County',
    'nandi hills': 'Nandi County',
    'narok east': 'Narok County',
    'narok north': 'Narok County',
    'narok south': 'Narok County',
    'narok west': 'Narok County',
    'transmara': 'Narok County',
    'trans mara': 'Narok County',
    'transmara west': 'Narok County',
    'transmara east': 'Narok County',
    'trans mara west': 'Narok County',
    'trans mara east': 'Narok County',
    'navakholo': 'Kakamega County',
    'ndaragwa': 'Nyandarua County',
    'ndhiwa': 'Homa Bay County',
    'ndia': 'Kirinyaga County',
    'nithi': 'Tharaka-Nithi County',
    'njoro': 'Nakuru County',
    'north horr': 'Marsabit County',
    'north imenti': 'Meru County',
    'north mugirango': 'Nyamira County',
    'nyakach': 'Kisumu County',
    'nyali': 'Mombasa County',
    'nyando': 'Kisumu County',
    'nyaribari chache': 'Kisii County',
    'nyaribari masaba': 'Kisii County',
    'nyatike': 'Migori County',
    'nyeri town': 'Nyeri County',
    'ol jorok': 'Nyandarua County',
    'ol kalou': 'Nyandarua County',
    'othaya': 'Nyeri County',
    'pokot south': 'West Pokot County',
    'rabai': 'Kilifi County',
    'rangwe': 'Homa Bay County',
    'rarieda': 'Siaya County',
    'rongai': 'Nakuru County',
    'rongo': 'Migori County',
    'roysambu': 'Nairobi County',
    'ruaraka': 'Nairobi County',
    'ruiru': 'Kiambu County',
    'runyenjes': 'Embu County',
    'sabatia': 'Vihiga County',
    'saboti': 'Trans Nzoia County',
    'saku': 'Marsabit County',
    'samburu east': 'Samburu County',
    'samburu north': 'Samburu County',
    'samburu west': 'Samburu County',
    'seme': 'Kisumu County',
    'shinyalu': 'Kakamega County',
    'siakago': 'Embu County',
    'sigor': 'West Pokot County',
    'sigowet/soin': 'Kericho County',
    'sirisia': 'Bungoma County',
    'sotik': 'Bomet County',
    'south imenti': 'Meru County',
    'south mugirango': 'Kisii County',
    'soy': 'Uasin Gishu County',
    'starehe': 'Nairobi County',
    'suba north': 'Homa Bay County',
    'suba south': 'Homa Bay County',
    'subukia': 'Nakuru County',
    'suna east': 'Migori County',
    'suna west': 'Migori County',
    'tarbaj': 'Wajir County',
    'taveta': 'Taita-Taveta County',
    'teso north': 'Busia County',
    'teso south': 'Busia County',
    'tetu': 'Nyeri County',
    'tharaka': 'Tharaka-Nithi County',
    'thika town': 'Kiambu County',
    'tiaty': 'Baringo County',
    'tigania east': 'Meru County',
    'tigania west': 'Meru County',
    'tinderet': 'Nandi County',
    'tongaren': 'Bungoma County',
    'turbo': 'Uasin Gishu County',
    'turkana central': 'Turkana County',
    'turkana east': 'Turkana County',
    'turkana north': 'Turkana County',
    'turkana south': 'Turkana County',
    'turkana west': 'Turkana County',
    'ugenya': 'Siaya County',
    'ugunja': 'Siaya County',
    'uriri': 'Migori County',
    'vihiga': 'Vihiga County',
    'voi': 'Taita-Taveta County',
    'wajir east': 'Wajir County',
    'wajir north': 'Wajir County',
    'wajir south': 'Wajir County',
    'wajir west': 'Wajir County',
    'webuye east': 'Bungoma County',
    'webuye west': 'Bungoma County',
    'west mugirango': 'Nyamira County',
    'westlands': 'Nairobi County',
    'wundanyi': 'Taita-Taveta County',
    'yatta': 'Machakos County',
})
