# Role and group names for NAWA

ROLE_SUPERADMIN = 'SuperAdmin'
ROLE_ADMIN = 'Admin'
ROLE_SUPERVISOR = 'Supervisor'
ROLE_DISPATCHER = 'Dispatcher'
ROLE_FIELD_OFFICER = 'FieldOfficer'
ROLE_ANALYST = 'Analyst'
ROLE_REPORTER = 'Reporter'
ROLE_EXTERNAL = 'ExternalAgency'

ALL_ROLES = [
	ROLE_SUPERADMIN,
	ROLE_ADMIN,
	ROLE_SUPERVISOR,
	ROLE_DISPATCHER,
	ROLE_FIELD_OFFICER,
	ROLE_ANALYST,
	ROLE_REPORTER,
	ROLE_EXTERNAL,
]

